@extends('layouts.app')
@section('title', 'Cash Flow Report')
@section('content')
<div class="container mx-auto rounded-xl bg-white p-5 shadow-md sm:p-8">
    <div class="flex flex-wrap justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[.16em] text-orange-600">Financial reporting</p><h1 class="mt-1 text-2xl font-semibold">Cash flow report</h1><p class="mt-1 text-sm text-slate-500">Actual collections and recorded expenses for the selected period.</p></div><a class="h-fit rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white" href="{{ route('reports.excel', array_merge(['report' => 'cashflow'], request()->query())) }}">Download Excel</a></div>
    <form class="my-6 flex flex-wrap items-end gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4"><label class="text-sm font-medium">From <input class="mt-1 block rounded-lg border-slate-300" type="date" name="start_date" value="{{ $startDate }}"></label><label class="text-sm font-medium">To <input class="mt-1 block rounded-lg border-slate-300" type="date" name="end_date" value="{{ $endDate }}"></label><button class="rounded-lg bg-orange-600 px-4 py-2 text-sm font-semibold text-white">Apply</button></form>
    <div class="mb-6 grid gap-4 sm:grid-cols-3"><div class="rounded-xl border border-emerald-100 bg-emerald-50 p-5"><p class="text-sm text-emerald-700">Cash in</p><p class="text-2xl font-bold">Tsh {{ number_format($cashIn,2) }}</p></div><div class="rounded-xl border border-red-100 bg-red-50 p-5"><p class="text-sm text-red-700">Cash out</p><p class="text-2xl font-bold">Tsh {{ number_format($cashOut,2) }}</p></div><div class="rounded-xl border border-blue-100 bg-blue-50 p-5"><p class="text-sm text-blue-700">Net cash flow</p><p class="text-2xl font-bold">Tsh {{ number_format($netCashFlow,2) }}</p></div></div>
    <div class="table-scroll"><table class="responsive-table min-w-full"><thead><tr><th class="p-3 text-left">Date</th><th class="p-3 text-left">Type</th><th class="p-3 text-left">Reference</th><th class="p-3 text-right">Cash in</th><th class="p-3 text-right">Cash out</th></tr></thead><tbody>@forelse($rows as $row)<tr><td class="p-3">{{ $row->date->format('d M Y H:i') }}</td><td class="p-3">{{ $row->type }}</td><td class="p-3">{{ $row->reference }}</td><td class="p-3 text-right">{{ $row->inflow ? 'Tsh '.number_format($row->inflow,2) : '—' }}</td><td class="p-3 text-right">{{ $row->outflow ? 'Tsh '.number_format($row->outflow,2) : '—' }}</td></tr>@empty<tr><td colspan="5" class="p-6 text-center text-slate-500">No cash movements for this period.</td></tr>@endforelse</tbody></table></div>
</div>
@endsection
