@extends('layouts.app')
@section('title', 'Expense Report')
@section('content')
<div class="container mx-auto mb-3 flex justify-end"><a class="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white" href="{{ route('reports.excel', array_merge(['report' => 'expenses'], request()->query())) }}">Download Excel</a></div>
<div class="container mx-auto bg-white p-5 sm:p-8 rounded-xl shadow-md"><div class="mb-7"><p class="text-xs font-semibold uppercase tracking-[.16em] text-orange-600">Financial reporting</p><h1 class="mt-1 text-2xl font-semibold">Expense report</h1><p class="mt-1 text-sm text-slate-500">Review spending by period and category.</p></div>
<form class="mb-6 flex flex-wrap items-end gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4"><label class="text-sm font-medium">From <input class="mt-1 block rounded-lg border-slate-300" type="date" name="start_date" value="{{ $startDate }}"></label><label class="text-sm font-medium">To <input class="mt-1 block rounded-lg border-slate-300" type="date" name="end_date" value="{{ $endDate }}"></label><button class="rounded-lg bg-orange-600 px-4 py-2.5 text-sm font-semibold text-white">Apply</button></form>
<div class="mb-6 grid gap-4 sm:grid-cols-2"><div class="rounded-xl border border-red-100 bg-red-50 p-5"><p class="text-sm text-red-700">Total expenses</p><p class="mt-1 text-2xl font-bold">Tsh {{ number_format($totalExpenses, 2) }}</p></div><div class="rounded-xl border border-slate-200 p-5"><p class="text-sm text-slate-500">Top expense category</p><p class="mt-1 text-lg font-semibold">{{ $byCategory->first()->category ?? 'No expenses' }}</p></div></div>
<div class="table-scroll"><table class="responsive-table min-w-full"><thead><tr><th class="p-3 text-left">Date</th><th class="p-3 text-left">Category</th><th class="p-3 text-left">Description</th><th class="p-3 text-right">Amount</th></tr></thead><tbody>@forelse($expenses as $expense)<tr><td class="p-3">{{ \Carbon\Carbon::parse($expense->expense_date)->format('d M Y') }}</td><td class="p-3">{{ $expense->category }}</td><td class="p-3">{{ $expense->description }}</td><td class="p-3 text-right">Tsh {{ number_format($expense->amount,2) }}</td></tr>@empty<tr><td colspan="4" class="p-6 text-center text-slate-500">No expenses for this period.</td></tr>@endforelse</tbody></table></div><div class="mt-5">{{ $expenses->links('pagination::tailwind') }}</div></div>
@endsection
