@csrf
@if(isset($motorService)) @method('PUT') @endif
<div class="grid gap-5 md:grid-cols-2">
    @if(!($isMechanic ?? false))
    <label class="text-sm font-medium">Vehicle<select name="vehicle_id" required class="mt-1 w-full rounded-lg border-slate-300"><option value="">Select a registered vehicle</option>@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}" @selected(old('vehicle_id', $motorService->vehicle_id ?? request('vehicle_id', '')) == $vehicle->id)>{{ $vehicle->registration_number }} — {{ $vehicle->make }} {{ $vehicle->model }} ({{ $vehicle->customer_name }})</option>@endforeach</select></label>
    <label class="text-sm font-medium">Assigned mechanic<select name="mechanic_id" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Unassigned</option>@foreach($mechanics as $mechanic)<option value="{{ $mechanic->id }}" @selected(old('mechanic_id', $motorService->mechanic_id ?? '') == $mechanic->id)>{{ $mechanic->name }}</option>@endforeach</select></label>
    <label class="text-sm font-medium">Service date<input type="date" name="service_date" required value="{{ old('service_date', isset($motorService) ? $motorService->service_date->format('Y-m-d') : now()->format('Y-m-d')) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="text-sm font-medium">Diagnosis due by<input type="date" name="diagnosis_due_date" value="{{ old('diagnosis_due_date', isset($motorService) && $motorService->diagnosis_due_date ? $motorService->diagnosis_due_date->format('Y-m-d') : '') }}" class="mt-1 w-full rounded-lg border-slate-300"><span class="mt-1 block text-xs font-normal text-slate-500">Optional deadline for the mechanic’s diagnosis.</span></label>
    @endif
    <label class="text-sm font-medium">Status<select name="status" class="mt-1 w-full rounded-lg border-slate-300">@foreach(['received'=>'Received','diagnosing'=>'Diagnosing','in_progress'=>'In progress','waiting_parts'=>'Waiting for parts','completed'=>'Completed','cancelled'=>'Cancelled'] as $value=>$label)<option value="{{ $value }}" @selected(old('status', $motorService->status ?? 'received') === $value)>{{ $label }}</option>@endforeach</select></label>
</div>
@if($isMechanic ?? false)<div class="mt-5 rounded-lg border border-slate-200 bg-slate-50 p-4"><p class="text-sm font-medium">Vehicle: {{ $motorService->vehicle->registration_number }} — {{ $motorService->vehicle->make }} {{ $motorService->vehicle->model }}</p><p class="mt-1 text-sm text-slate-600">Customer complaint: {{ $motorService->complaint }}</p><p class="mt-1 text-sm text-slate-600">Diagnosis due: {{ $motorService->diagnosis_due_date?->format('d M Y') ?? 'Not set' }}</p></div>@else<label class="mt-5 block text-sm font-medium">Customer complaint<textarea name="complaint" required rows="3" class="mt-1 w-full rounded-lg border-slate-300">{{ old('complaint', $motorService->complaint ?? '') }}</textarea></label>@endif
<div class="mt-5 grid gap-5 md:grid-cols-2"><label class="text-sm font-medium">Diagnosis<textarea name="diagnosis" rows="3" class="mt-1 w-full rounded-lg border-slate-300">{{ old('diagnosis', $motorService->diagnosis ?? '') }}</textarea></label><label class="text-sm font-medium">Work performed<textarea name="work_performed" rows="3" class="mt-1 w-full rounded-lg border-slate-300">{{ old('work_performed', $motorService->work_performed ?? '') }}</textarea></label></div>
@if(!($isMechanic ?? false))<div class="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><label class="text-sm font-medium">Labour (Tsh)<input name="labor_amount" type="number" min="0" step="0.01" required value="{{ old('labor_amount', $motorService->labor_amount ?? 0) }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="text-sm font-medium">Parts (Tsh)<input name="parts_amount" type="number" min="0" step="0.01" required value="{{ old('parts_amount', $motorService->parts_amount ?? 0) }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="text-sm font-medium">Discount (Tsh)<input name="discount_amount" type="number" min="0" step="0.01" required value="{{ old('discount_amount', $motorService->discount_amount ?? 0) }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="text-sm font-medium">Amount paid (Tsh)<input name="amount_paid" type="number" min="0" step="0.01" required value="{{ old('amount_paid', $motorService->amount_paid ?? 0) }}" class="mt-1 w-full rounded-lg border-slate-300"></label></div>@endif
<label class="mt-5 block text-sm font-medium">Internal notes<textarea name="notes" rows="2" class="mt-1 w-full rounded-lg border-slate-300">{{ old('notes', $motorService->notes ?? '') }}</textarea></label>
<div class="mt-6 flex gap-3"><button class="rounded-lg bg-orange-600 px-5 py-2.5 font-semibold text-white">Save job card</button><a href="{{ route('motor-services.index') }}" class="rounded-lg border px-5 py-2.5">Cancel</a></div>
